'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import {api,type Category,type Product} from '@/lib/api';
const blank={categoryId:1,name:'',slug:'',description:'',price:0,imageUrl:'',inventory:0,featured:false,active:true};
export default function Admin(){
 const [products,setProducts]=useState<Product[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [form,setForm]=useState(blank);const [editing,setEditing]=useState<number|null>(null);const [message,setMessage]=useState('');
 const load=async()=>{try{setProducts((await api<{data:Product[]}>('/admin/products')).data);setCategories((await api<{data:Category[]}>('/categories')).data)}catch(e){setMessage(e instanceof Error?e.message:'Unable to load admin.')}};useEffect(()=>{load()},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setMessage('Saving…');try{await api(editing?`/admin/products/${editing}`:'/admin/products',{method:editing?'PUT':'POST',body:JSON.stringify(form)});setForm({...blank,categoryId:categories[0]?.id||1});setEditing(null);setMessage('Product saved.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.')}};
 const edit=(p:Product)=>{setEditing(p.id);setForm({categoryId:p.categoryId,name:p.name,slug:p.slug,description:p.description,price:p.price,imageUrl:p.imageUrl,inventory:p.inventory,featured:p.featured,active:p.active});scrollTo({top:0,behavior:'smooth'})};
 const deactivate=async(id:number)=>{if(!confirm('Deactivate this product?'))return;await api(`/admin/products/${id}`,{method:'DELETE'});setMessage('Product deactivated.');load()};
 return <main className="section admin"><span className="eyebrow">STORE MANAGEMENT</span><h1 className="page-title">Product admin</h1><p><Link href="/admin/orders">Manage customer orders →</Link></p><form className="admin-form" onSubmit={submit}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug<input required pattern="[a-z0-9-]+" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Category<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:Number(e.target.value)})}>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Price<input required min="0" step="0.01" type="number" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>Inventory<input required min="0" type="number" value={form.inventory} onChange={e=>setForm({...form,inventory:Number(e.target.value)})}/></label><label>Image URL<input required type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></label><label className="wide">Description<textarea required minLength={20} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured product</label><button className="button" type="submit">{editing?'Update product':'Create product'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</form>{message&&<div className="notice" role="status">{message}</div>}<div className="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.categoryName}</td><td>${p.price.toFixed(2)}</td><td>{p.inventory}</td><td>{p.active?'Active':'Inactive'}</td><td><button onClick={()=>edit(p)}>Edit</button> {p.active&&<button onClick={()=>deactivate(p.id)}>Deactivate</button>}</td></tr>)}</tbody></table></div></main>
}
